# Generated by Django 4.2.2 on 2023-06-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='bot_response',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(default='New recommendation about...', max_length=255),
        ),
    ]
